### ISSUE TITLE
[QUESTION]:如何将日志输出到victorialogs

### ISSUE THREAD

**Issue by ktpktr0** [alibaba/loongcollector#1365]
victorialogs官方filebeat配置
```
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: [ "http://victorialogs:9428/insert/elasticsearch/" ]
  worker: 5
  parameters:
    _msg_field: "message"
    _time_field: "@timestamp"
    _stream_fields: "container.name"

http:
  enabled: true
  host: 0.0.0.0
  port: 5066
```

我使用ilogtail配置
```
enable: true
inputs:
  - Type: input_file
    FilePaths:
      - /var/log/*/*.log
flushers:
  - Type: flusher_elasticsearch
    Addresses:
      - "http://victorialogs:9428/insert/elasticsearch/"
    #Index: default
    #Authentication:
    #  PlainText:
    #    Username: user
    #    Password: 123456
    HTTPConfig:
        MaxIdleConnsPerHost: 10
        ResponseHeaderTimeout: Second
  - Type: flusher_stdout
```
无法输出日志到victorialogs
