### ISSUE TITLE
[BUG]: Could not send OTLP data with specific header using OTLP flusher

### ISSUE THREAD

**Issue by ralf0131** [alibaba/loongcollector#2011]
**Describe the bug**
I am using LoongCollector to send OTLP data to a backend server.  The data flow is as follows:
 go application with [compile time instrumentation](https://github.com/alibaba/opentelemetry-go-auto-instrumentation/issues)  -> LoongCollector -> Backend OTLP server
Since the back server need authentication, a `Authentication` header is needed. 
I have configured the OTLP flusher to add a specific header, however it will not take any effect.

**LoongCollector Running Environment**
Please provide the following information:

- LoongCollector version:
Building from the source code from scratch.
  
- Yaml configuration:
```
---
enable: true
global:
  StructureType: v2
inputs:
  - Type: service_otlp
    Protocals:
      GRPC:
        Endpoint: 0.0.0.0:4316
flushers:
  - Type: flusher_otlp
    Traces:
      Endpoint: http://xxx:8090
      Headers:
        Authentication: xxx

```

- ilogtail.LOG:

- logtail_plugin.LOG:

```
2025-01-03 16:59:10 [ERR] [plugin_runner_v2.go:376] [runFlusherInternal] [otlp/1]       AlarmType:FLUSH_DATA_ALARM      flush data error:       :rpc error: code = PermissionDenied desc =      logstore:       config:otlp
```

#### Investigation
Using tcpdump to dump the data to server, we found that the `Authentication` header is missing, there we believe that this is a bug.
