### ISSUE TITLE
[BUG]: 输入插件使用Syslog，不能配合扩展处理插件使用

### ISSUE THREAD

**Issue by OoMaXinyiOo** [alibaba/loongcollector#2104]
```
enable: true
inputs:
  - Type: service_syslog
    Address: udp://0.0.0.0:9009
processors:
  - Type: processor_regex
    SourceKey: content
    Regex: .*key\S+\s*(\d+).*
    Keys:
      - aaaaa
flushers:
  - Type: flusher_stdout
    OnlyStdout: true
```

扩展处理插件不生效
