### ISSUE TITLE
[FEATURE]:k8s支持声明式采集

### ISSUE THREAD

**Issue by wingyiu** [alibaba/loongcollector#2124]
Annotations["ilogtail.io/scrape"] = "true"
Annotations["ilogtail.io/config"] = "{}"

**Comment by Takuka0311** [comment]
可以描述更详细一些吗？

**Comment by shalousun** [comment]
> 可以描述更详细一些吗？

His meaning should be to achieve Filebeat-like declarative collection

# Adding Multi-line Annotations to Deployment

If you deploy your component to a Kubernetes cluster and want Filebeat's `hints system` to automatically recognize multi-line logs, you need to add `multiline annotations` to the deployment template of your component. For example:

```
annotations:
  co.elastic.logs/multiline.type: 'pattern'
  co.elastic.logs/multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  co.elastic.logs/multiline.negate: 'true'
  co.elastic.logs/multiline.match: 'after'
```

For other [configuration options](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html), please refer to the official documentation of Filebeat.
