### ISSUE TITLE
[BUG]:containerd 2.0.x cannot collect container logs

### ISSUE THREAD

**Issue by clcc2019** [alibaba/loongcollector#2177]
**Describe the bug**
containerd 2.0.x version fails to collect container logs correctly.

**iLogtail Running Environment**

- ilogtail version:3.0.5
  
- Yaml configuration:
```yaml
enable: true
inputs:
  - Type: service_docker_stdout
    Stderr: false
    Stdout: true
    IncludeK8sLabel:
      app.kubernetes.io/name: ingress-nginx
processors:
  - Type: processor_json
    SourceKey: content
    KeepSource: true
    ExpandDepth: 1
    ExpandConnector: ""
flushers:
  - Type: flusher_stdout
    OnlyStdout: true
```
- ilogtail.LOG:
```yaml
2025-04-09 07:24:18 [INF] [container_discover_controller.go:253] [Init] init docker center, max fetchOne count per second:200
2025-04-09 07:24:18 [ERR] [docker_center.go:1176] [dockerCenterRecover] AlarmType:PLUGIN_RUNTIME_ALARM	docker center runtime error:runtime error: invalid memory address or nil pointer dereference	stack:goroutine 99 [running]:
github.com/alibaba/ilogtail/pkg/helper.dockerCenterRecover()
	/src/pkg/helper/docker_center.go:1173 +0x71
panic({0x7ff6ba005e80, 0x7ff6bc49dd80})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/docker/docker/client.(*Client).getAPIPath(0x37300000?, {0x7ff6ba60f318?, 0xc000082048?}, {0x7ff6b93a63e8, 0x10}, 0xc0013ab818?)
	/opt/go/pkg/mod/github.com/docker/docker@v20.10.23+incompatible/client/client.go:180 +0x4e
github.com/docker/docker/client.(*Client).sendRequest(0x7ff6b9381251?, {0x7ff6ba60f318, 0xc000082048}, {0x7ff6b9379b7c, 0x3}, {0x7ff6b93a63e8?, 0xc0000d0620?}, 0x7ff6bcd4cde0?, {0x0, 0x0}, ...)
	/opt/go/pkg/mod/github.com/docker/docker@v20.10.23+incompatible/client/request.go:109 +0x78
github.com/docker/docker/client.(*Client).get(...)
	/opt/go/pkg/mod/github.com/docker/docker@v20.10.23+incompatible/client/request.go:37
github.com/docker/docker/client.(*Client).ContainerList(0x0, {0x7ff6ba60f318, 0xc000082048}, {0x0, 0x0, 0x1, 0x0, {0x0, 0x0}, {0x0, ...}, ...})
	/opt/go/pkg/mod/github.com/docker/docker@v20.10.23+incompatible/client/container_list.go:48 +0x558
github.com/alibaba/ilogtail/pkg/helper.(*DockerCenter).fetchAll(0xc0001a20a0)
	/src/pkg/helper/docker_center.go:1051 +0xf3
github.com/alibaba/ilogtail/pkg/helper.(*ContainerDiscoverManager).fetchDocker(...)
	/src/pkg/helper/container_discover_controller.go:111
github.com/alibaba/ilogtail/pkg/helper.(*ContainerDiscoverManager).Init(0xc000505cc8)
	/src/pkg/helper/container_discover_controller.go:254 +0x97f
github.com/alibaba/ilogtail/pkg/helper.getDockerCenterInstance.func1.1()
	/src/pkg/helper/docker_center.go:669 +0x6f
created by github.com/alibaba/ilogtail/pkg/helper.getDockerCenterInstance.func1
	/src/pkg/helper/docker_center.go:665 +0xbe

goroutine 79 [runnable]:
sync.runtime_notifyListWait(0xc0002f3650, 0x3d)
	/usr/local/go/src/runtime/sema.go:517 +0x14c
sync.(*Cond).Wait(0x7a120?)
	/usr/local/go/src/sync/cond.go:70 +0x8c
github.com/cihub/seelog.(*asyncTimerLogger).processItem(0xc0002486c0)
	/opt/go/pkg/mod/github.
```
- logtail_plugin.LOG:
