### ISSUE TITLE
[ENHANCEMENT]: Support json encoding when converter protocol is raw

### ISSUE THREAD

**Issue by xuzhijvn** [alibaba/loongcollector#2207]
**Concisely describe the proposed feature**

Support json encoding when converter protocol is raw

**Describe the solution you'd like (if any)**

Currently, [converter](https://github.com/alibaba/loongcollector/blob/main/pkg/protocol/converter/converter.go) does not support the case where the protocol is raw and the encoding is json.

For example, `service_http_server` receives data, `processor_custom` processes it, and `flusher_http` sends it out: 

```
enable: true
global:
  StructureType: v2
inputs:
  - Type: service_http_server
    Format: "raw"
    Address: "http://0.0.0.0:12345"
processors:
  - Type: processor_custom
    URL: "https://postman-echo.com/post"
flushers:
  - Type: flusher_stdout
    OnlyStdout: true
  - Type: flusher_http
    RemoteURL: "http://localhost:3000/api/public/ingestion"
    Convert:
      Protocol: raw
      Encoding: json 
    Concurrency: 10
    QueueCapacity: 4096
    DropEventWhenQueueFull: true
```
